# Generated by Django 5.0.7 on 2024-07-27 22:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_servicecategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicecategory',
            old_name='category',
            new_name='categoryName',
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
