# Generated by Django 5.0.7 on 2024-07-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_drugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
