# Generated by Django 5.0.7 on 2024-08-01 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_drugs_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugs',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Providedservices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.servicecategory')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.service')),
            ],
        ),
    ]
