# Generated by Django 5.0.7 on 2024-07-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biodata',
            name='Date',
        ),
        migrations.AddField(
            model_name='biodata',
            name='District',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='biodata',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='height',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='biodata',
            name='sex',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='biodata',
            name='tribe',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='biodata',
            name='weight',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='Address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='Age',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='Emailaddress',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='Firstname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='Othernames',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='Phone',
            field=models.CharField(default='', max_length=100),
        ),
    ]
