# Generated by Django 5.0.7 on 2024-07-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_biodata_day_of_week_alter_biodata_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
