# Generated by Django 5.0.7 on 2024-07-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_rename_category_servicecategory_categoryname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicecategory',
            old_name='categoryName',
            new_name='category',
        ),
    ]
