# Generated by Django 5.0.7 on 2024-08-01 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_remove_biodata_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='providedservices',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.biodata'),
        ),
    ]
